steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/api.cloudrun.Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/trax-api:latest
      - .

images:
  - gcr.io/$PROJECT_ID/trax-api:latest