import {
  Employee,
  Geofence,
  AttendanceRecord,
  DashboardStats,
  LiveTrackingEmployee,
} from "@/lib/types/trackingTypes";

export const mockGeofences: Geofence[] = [
  {
    id: 1,
    name: "المقر الرئيسي",
    address: "الرياض، حي العليا، طريق الملك فهد",
    lat: 24.7136,
    lng: 46.6753,
    radius: 150,
    color: "#2563EB",
    active: true,
  },
  {
    id: 2,
    name: "فرع جدة",
    address: "جدة، حي الروضة، طريق المدينة",
    lat: 21.4858,
    lng: 39.1925,
    radius: 100,
    color: "#16A34A",
    active: true,
  },
  {
    id: 3,
    name: "مستودع الدمام",
    address: "الدمام، حي الصناعية",
    lat: 26.4207,
    lng: 50.0888,
    radius: 200,
    color: "#F59E0B",
    active: true,
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 1,
    name: "أحمد محمد",
    email: "ahmed@trax.com",
    phone: "+966500000001",
    role: "manager",
    department: "الإدارة",
    avatar: null,
    geofenceId: 1,
    status: "active",
    currentLat: 24.7136,
    currentLng: 46.6753,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-001",
  },
  {
    id: 2,
    name: "خالد العتيبي",
    email: "khalid@trax.com",
    phone: "+966500000002",
    role: "employee",
    department: "المبيعات",
    avatar: null,
    geofenceId: 1,
    status: "active",
    currentLat: 24.7145,
    currentLng: 46.676,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-002",
  },
  {
    id: 3,
    name: "سارة الزهراني",
    email: "sara@trax.com",
    phone: "+966500000003",
    role: "supervisor",
    department: "الموارد البشرية",
    avatar: null,
    geofenceId: 1,
    status: "active",
    currentLat: 24.7128,
    currentLng: 46.6748,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-003",
  },
  {
    id: 4,
    name: "فهد القحطاني",
    email: "fahd@trax.com",
    phone: "+966500000004",
    role: "employee",
    department: "التسويق",
    avatar: null,
    geofenceId: 2,
    status: "active",
    currentLat: 21.4858,
    currentLng: 39.1925,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-004",
  },
  {
    id: 5,
    name: "نورة الشمري",
    email: "noura@trax.com",
    phone: "+966500000005",
    role: "employee",
    department: "المالية",
    avatar: null,
    geofenceId: 1,
    status: "active",
    currentLat: 24.715,
    currentLng: 46.6755,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-005",
  },
  {
    id: 6,
    name: "عبدالله الدوسري",
    email: "abdullah@trax.com",
    phone: "+966500000006",
    role: "employee",
    department: "المستودع",
    avatar: null,
    geofenceId: 3,
    status: "active",
    currentLat: 26.4207,
    currentLng: 50.0888,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-006",
  },
  {
    id: 7,
    name: "ريم الحربي",
    email: "reem@trax.com",
    phone: "+966500000007",
    role: "employee",
    department: "المبيعات",
    avatar: null,
    geofenceId: 2,
    status: "inactive",
    currentLat: null,
    currentLng: null,
    lastSeen: null,
    employeeNumber: "EMP-007",
  },
  {
    id: 8,
    name: "ماجد الغامدي",
    email: "majed@trax.com",
    phone: "+966500000008",
    role: "employee",
    department: "التسويق",
    avatar: null,
    geofenceId: 1,
    status: "active",
    currentLat: 24.7132,
    currentLng: 46.6758,
    lastSeen: new Date().toISOString(),
    employeeNumber: "EMP-008",
  },
];

const today = new Date().toISOString().split("T")[0];

export const mockAttendance: AttendanceRecord[] = [
  {
    id: 1,
    employeeId: 1,
    employeeName: "أحمد محمد",
    date: today,
    checkInTime: "08:00",
    checkOutTime: null,
    status: "present",
    checkInLat: 24.7136,
    checkInLng: 46.6753,
    geofenceName: "المقر الرئيسي",
    lateMinutes: 0,
    workedHours: 0,
  },
  {
    id: 2,
    employeeId: 2,
    employeeName: "خالد العتيبي",
    date: today,
    checkInTime: "08:25",
    checkOutTime: null,
    status: "late",
    checkInLat: 24.7145,
    checkInLng: 46.676,
    geofenceName: "المقر الرئيسي",
    lateMinutes: 25,
    workedHours: 0,
  },
  {
    id: 3,
    employeeId: 3,
    employeeName: "سارة الزهراني",
    date: today,
    checkInTime: "07:55",
    checkOutTime: null,
    status: "present",
    checkInLat: 24.7128,
    checkInLng: 46.6748,
    geofenceName: "المقر الرئيسي",
    lateMinutes: 0,
    workedHours: 0,
  },
  {
    id: 4,
    employeeId: 4,
    employeeName: "فهد القحطاني",
    date: today,
    checkInTime: "08:10",
    checkOutTime: null,
    status: "present",
    checkInLat: 21.4858,
    checkInLng: 39.1925,
    geofenceName: "فرع جدة",
    lateMinutes: 0,
    workedHours: 0,
  },
  {
    id: 5,
    employeeId: 5,
    employeeName: "نورة الشمري",
    date: today,
    checkInTime: "08:45",
    checkOutTime: null,
    status: "late",
    checkInLat: 24.715,
    checkInLng: 46.6755,
    geofenceName: "المقر الرئيسي",
    lateMinutes: 45,
    workedHours: 0,
  },
  {
    id: 6,
    employeeId: 6,
    employeeName: "عبدالله الدوسري",
    date: today,
    checkInTime: "07:50",
    checkOutTime: null,
    status: "present",
    checkInLat: 26.4207,
    checkInLng: 50.0888,
    geofenceName: "مستودع الدمام",
    lateMinutes: 0,
    workedHours: 0,
  },
  {
    id: 7,
    employeeId: 7,
    employeeName: "ريم الحربي",
    date: today,
    checkInTime: null,
    checkOutTime: null,
    status: "absent",
    checkInLat: null,
    checkInLng: null,
    geofenceName: null,
    lateMinutes: 0,
    workedHours: 0,
  },
  {
    id: 8,
    employeeId: 8,
    employeeName: "ماجد الغامدي",
    date: today,
    checkInTime: "08:05",
    checkOutTime: null,
    status: "present",
    checkInLat: 24.7132,
    checkInLng: 46.6758,
    geofenceName: "المقر الرئيسي",
    lateMinutes: 0,
    workedHours: 0,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalEmployees: 8,
  activeEmployees: 7,
  inactiveEmployees: 1,
  presentToday: 5,
  absentToday: 1,
  lateToday: 2,
  checkedOutToday: 0,
  onTimeRate: 71.4,
  avgCheckInTime: "08:11",
  avgWorkedHours: 7.5,
  totalGeofences: 3,
};

export const mockLiveTracking: LiveTrackingEmployee[] = [
  {
    id: 1,
    name: "أحمد محمد",
    lat: 24.7136,
    lng: 46.6753,
    status: "inside_geofence",
    geofenceName: "المقر الرئيسي",
    lastSeen: new Date().toISOString(),
    batteryLevel: 85,
  },
  {
    id: 2,
    name: "خالد العتيبي",
    lat: 24.7145,
    lng: 46.676,
    status: "inside_geofence",
    geofenceName: "المقر الرئيسي",
    lastSeen: new Date().toISOString(),
    batteryLevel: 62,
  },
  {
    id: 3,
    name: "سارة الزهراني",
    lat: 24.7128,
    lng: 46.6748,
    status: "inside_geofence",
    geofenceName: "المقر الرئيسي",
    lastSeen: new Date().toISOString(),
    batteryLevel: 91,
  },
  {
    id: 4,
    name: "فهد القحطاني",
    lat: 21.4858,
    lng: 39.1925,
    status: "inside_geofence",
    geofenceName: "فرع جدة",
    lastSeen: new Date().toISOString(),
    batteryLevel: 45,
  },
  {
    id: 5,
    name: "نورة الشمري",
    lat: 24.715,
    lng: 46.6755,
    status: "inside_geofence",
    geofenceName: "المقر الرئيسي",
    lastSeen: new Date().toISOString(),
    batteryLevel: 73,
  },
  {
    id: 6,
    name: "عبدالله الدوسري",
    lat: 26.4207,
    lng: 50.0888,
    status: "inside_geofence",
    geofenceName: "مستودع الدمام",
    lastSeen: new Date().toISOString(),
    batteryLevel: 28,
  },
  {
    id: 8,
    name: "ماجد الغامدي",
    lat: 24.72,
    lng: 46.68,
    status: "outside_geofence",
    geofenceName: null,
    lastSeen: new Date().toISOString(),
    batteryLevel: null,
  },
];
